### ISSUE TITLE
What is the proxy needed for?

### ISSUE THREAD

**Issue by flocsy** [lswiderski/mi-scale-exporter#12]
Hi, this is not a problem with the app, but rather I don't understand why would anyone need the proxy, when it works (and it does work perfectly, I tried it) without the proxy when it reports straight to the garmin api?

**Comment by lswiderski** [comment]
Hi,

There are a few reasons:

In the previous version of the app there were no direct calls to the Garmin API. Everything went through proxy web api. When I started the project, there was no currently working solution in C# to connect to Garmin and there was well maintained GO library for it. So it was easier to wrap it in web api and host it in container and pass data through it. Sometime later in issue #7 @Abasz forked and fixed the c# garmin api client and I implemented it in the app.

Both libraries use unofficial Garmin API (reverse engineered) and it can change at  any time. Since the GO version is better maintained for sure any possible fix for it will be released faster for it. This is why I left the proxy option in the app. If the c# client stops working, then anyone can bypass it.

The third reason is privacy. I'm not the author of the c# or GO client. If someone does not trust to it and does not want to share his username/password for garmin services, he can host his own garmin api client.

The fourth reason is customization. In your own version of host you add some logs collects for statistics and other metrics.

Hope that's help :)
