### ISSUE TITLE
Can't input decimal numbers manually

### ISSUE THREAD

**Issue by holecekjan** [lswiderski/mi-scale-exporter#13]
I wanted to fill a form manually. I can't input decimal numbers with a "," as a decimal separator. The Google keyboard enables only to use dot "." and the form require "," The result is I can't send decimal numbers to Garmin connect portal.

The solution is to accept , as well . as separator and change it to correct form internally before sending to Garmin.

Android 12, CS language settings, Google keyboard.

**Comment by lswiderski** [comment]
Hi @holecekjan 

Thanks for your feedback.

It will be fixed in the next release (probably this weekend). The code is already on the main branch. Both comma and dot will be accepted by the application, no matter what Gboard allows you to write. Somehow Gboard still allows to enter only dots, but this will no longer be a problem for the application.

**Comment by lswiderski** [comment]
Hi @holecekjan

Version 2.0.2 should work fine with this problem
https://github.com/lswiderski/mi-scale-exporter/releases/tag/v2.0.2

Please let me know if it works properly.

**Comment by holecekjan** [comment]
Hello Lukasz,
thank you for fixing decimal separator bug. I confirm that now I can manually input decimal values instead of integer value. Manual input is useful when you have measurement from external BIA device.
